[2024-08-06T21:46:57.311+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T21:41:53.601669+00:00 [queued]>
[2024-08-06T21:46:57.316+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T21:41:53.601669+00:00 [queued]>
[2024-08-06T21:46:57.317+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-06T21:46:57.317+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-08-06T21:46:57.317+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-06T21:46:57.321+0000] {taskinstance.py:1300} INFO - Executing <Task(DbtRunOperator): dbt_run> on 2024-08-06 21:41:53.601669+00:00
[2024-08-06T21:46:57.324+0000] {standard_task_runner.py:55} INFO - Started process 297 to run task
[2024-08-06T21:46:57.325+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'load_parquet_to_bq_dag', 'dbt_run', 'manual__2024-08-06T21:41:53.601669+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/load_dbt_dag.py', '--cfg-path', '/tmp/tmpdau3vx8q']
[2024-08-06T21:46:57.326+0000] {standard_task_runner.py:83} INFO - Job 62: Subtask dbt_run
[2024-08-06T21:46:57.348+0000] {task_command.py:388} INFO - Running <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T21:41:53.601669+00:00 [running]> on host cf0df9e834a7
[2024-08-06T21:46:57.369+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=miguel
AIRFLOW_CTX_DAG_ID=load_parquet_to_bq_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2024-08-06T21:41:53.601669+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-06T21:41:53.601669+00:00
[2024-08-06T21:46:57.369+0000] {dbt_hook.py:117} INFO - dbt run --profiles-dir /opt/dbt_project --models load_parquet_to_test
[2024-08-06T21:46:57.373+0000] {dbt_hook.py:126} INFO - Output:
[2024-08-06T21:46:58.233+0000] {dbt_hook.py:130} INFO - [0m21:46:58  Running with dbt=1.8.4
[2024-08-06T21:46:58.786+0000] {dbt_hook.py:130} INFO - [0m21:46:58  Registered adapter: bigquery=1.8.2
[2024-08-06T21:46:58.867+0000] {dbt_hook.py:130} INFO - [0m21:46:58  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-08-06T21:46:58.867+0000] {dbt_hook.py:130} INFO - There are 3 unused configuration paths:
[2024-08-06T21:46:58.868+0000] {dbt_hook.py:130} INFO - - models.prazos_project.staging
[2024-08-06T21:46:58.868+0000] {dbt_hook.py:130} INFO - - models.prazos_project.marts.core
[2024-08-06T21:46:58.868+0000] {dbt_hook.py:130} INFO - - models.prazos_project.marts.intermediate
[2024-08-06T21:46:58.960+0000] {dbt_hook.py:130} INFO - [0m21:46:58  Found 1 model, 1 source, 473 macros
[2024-08-06T21:46:58.961+0000] {dbt_hook.py:130} INFO - [0m21:46:58
[2024-08-06T21:47:00.301+0000] {dbt_hook.py:130} INFO - [0m21:47:00
[2024-08-06T21:47:00.302+0000] {dbt_hook.py:130} INFO - [0m21:47:00  Finished running  in 0 hours 0 minutes and 1.34 seconds (1.34s).
[2024-08-06T21:47:00.304+0000] {dbt_hook.py:130} INFO - [0m21:47:00  Encountered an error:
[2024-08-06T21:47:00.304+0000] {dbt_hook.py:130} INFO - Database Error
[2024-08-06T21:47:00.304+0000] {dbt_hook.py:130} INFO -   Invalid project ID 'prazos_project'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
[2024-08-06T21:47:01.162+0000] {dbt_hook.py:132} INFO - Command exited with return code 2
[2024-08-06T21:47:01.167+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 98, in execute
    self.create_hook().run_cli('run')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2024-08-06T21:47:01.169+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=load_parquet_to_bq_dag, task_id=dbt_run, execution_date=20240806T214153, start_date=20240806T214657, end_date=20240806T214701
[2024-08-06T21:47:01.174+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 62 for task dbt_run (dbt command failed; 297)
[2024-08-06T21:47:01.218+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-06T21:47:01.226+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
